const searchByRoomNo = `
    SELECT r2.ROOMID , r2.ROOMNO , CONCAT(u.FNAME , " " , u.LNAME) AS "FULLNAME" , u.TELNO , u.GENDER , u.IDCARDNO , u.DATEOFBIRTH , u.ADDRESS , cor.STARTDATE , cor.ENDDATE , r.CHECKINDATE , r.CHECKOUTDATE 
    FROM RENT r 
    JOIN USER u 
    ON r.USERID = u.USERID 
    JOIN CONTRACT_OF_RENT cor 
    ON r.CONTRACTOFRENTID = cor.CONTRACTOFRENTID 
    JOIN ROOM r2 
    ON r.ROOMID = r2.ROOMID 
    JOIN BUILDING b 
    ON r2.BUILDINGID = b.BUILDINGID 
    JOIN DORMITORY d 
    ON b.DORMID = d.DORMID 
    WHERE d.DORMID = :dormID
    AND r2.ROOMNO = :input
    ORDER BY cor.STARTDATE DESC;
`

const searchByTelNo = `
    SELECT r2.ROOMID , r2.ROOMNO , CONCAT(u.FNAME , " " , u.LNAME) AS "FULLNAME" , u.TELNO , u.GENDER , u.IDCARDNO , u.DATEOFBIRTH , u.ADDRESS , cor.STARTDATE , cor.ENDDATE , r.CHECKINDATE , r.CHECKOUTDATE 
    FROM RENT r 
    JOIN USER u 
    ON r.USERID = u.USERID 
    JOIN CONTRACT_OF_RENT cor 
    ON r.CONTRACTOFRENTID = cor.CONTRACTOFRENTID 
    JOIN ROOM r2 
    ON r.ROOMID = r2.ROOMID 
    JOIN BUILDING b 
    ON r2.BUILDINGID = b.BUILDINGID 
    JOIN DORMITORY d 
    ON b.DORMID = d.DORMID 
    WHERE d.DORMID = :dormID
    AND u.TELNO LIKE :input
    ORDER BY cor.STARTDATE DESC;
`

const searchByIdCardNo = `
    SELECT r2.ROOMID , r2.ROOMNO , CONCAT(u.FNAME , " " , u.LNAME) AS "FULLNAME" , u.TELNO , u.GENDER , u.IDCARDNO , u.DATEOFBIRTH , u.ADDRESS , cor.STARTDATE , cor.ENDDATE , r.CHECKINDATE , r.CHECKOUTDATE 
    FROM RENT r 
    JOIN USER u 
    ON r.USERID = u.USERID 
    JOIN CONTRACT_OF_RENT cor 
    ON r.CONTRACTOFRENTID = cor.CONTRACTOFRENTID 
    JOIN ROOM r2 
    ON r.ROOMID = r2.ROOMID 
    JOIN BUILDING b 
    ON r2.BUILDINGID = b.BUILDINGID 
    JOIN DORMITORY d 
    ON b.DORMID = d.DORMID 
    WHERE d.DORMID = :dormID
    AND u.IDCARDNO LIKE :input
    ORDER BY cor.STARTDATE DESC;
`

const searchByName = `
    SELECT r2.ROOMID , r2.ROOMNO , CONCAT(u.FNAME , " " , u.LNAME) AS "FULLNAME" , u.TELNO , u.GENDER , u.IDCARDNO , u.DATEOFBIRTH , u.ADDRESS , cor.STARTDATE , cor.ENDDATE , r.CHECKINDATE , r.CHECKOUTDATE 
    FROM RENT r 
    JOIN USER u 
    ON r.USERID = u.USERID 
    JOIN CONTRACT_OF_RENT cor 
    ON r.CONTRACTOFRENTID = cor.CONTRACTOFRENTID 
    JOIN ROOM r2 
    ON r.ROOMID = r2.ROOMID 
    JOIN BUILDING b 
    ON r2.BUILDINGID = b.BUILDINGID 
    JOIN DORMITORY d 
    ON b.DORMID = d.DORMID 
    WHERE d.DORMID = :dormID
    AND CONCAT(u.FNAME , " " , u.LNAME) LIKE :input
    ORDER BY 3 , cor.STARTDATE DESC;
`

module.exports = { searchByRoomNo, searchByTelNo, searchByIdCardNo, searchByName };